version: '3'
services:
  database:
    image: 'postgres:10.7'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5433:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

  api:
    build:
      context: .
    image: rails-api
    stdin_open: true
    tty: true
    depends_on:
      - 'database'
    environment:
        PORT: 4000
        RACK_ENV: 'development'
        RAILS_ENV: 'development'
        DATABASE_DEV_URL: "postgres://postgres:postgres@database:5432/rails_api"
    ports:
      - '4000:4000'
    volumes:
      - '$PWD:/home/app'

volumes:
  pgdata:
    external: true
